### PR TITLE
Fix for '//mask ?' resulting in pattern error

### PR DESCRIPTION
**Pull request by IronApollo**

### CODE REVIEW

**Comment by N0tMyFaultOG** [comment]
Fixes https://github.com/boy0001/FastAsyncWorldedit/issues/1079#issuecomment-433508811

**Comment by N0tMyFaultOG** [comment]
No, this fixes the error I mentioned above

**Comment by N0tMyFaultOG** [comment]
Fixes https://github.com/boy0001/FastAsyncWorldedit/issues/1177

**Comment by N0tMyFaultOG** [comment]
Fixes https://github.com/IntellectualSites/PlotSquared/issues/2144

**Comment by mibby** [comment]
@N0tMyFaultOG What about PlotSquared breaking getWorld(String) in Spigot 1.13 with FAWE 1.13?
https://github.com/IntellectualSites/PlotSquared/issues/2143

**Pull request merged**
