### PR TITLE
Changes to completely separate SyncTabCompleteListener from Paper

### PR DESCRIPTION
**Pull request by IronApollo**

### CODE REVIEW

**Comment by N0tMyFaultOG** [comment]
This should fix https://github.com/boy0001/FastAsyncWorldedit/issues/1161

**Comment by CloudeLecaw** [comment]
well so the Problem is because i use Spigot? and not paper? :3

**Comment by N0tMyFaultOG** [comment]
Will fix boy0001/FastAsyncWorldEdit/#1172

**Comment by N0tMyFaultOG** [comment]
Possibly fix for https://github.com/boy0001/FastAsyncWorldedit/issues/1172

**Pull request merged**
